name: Deploy to Google Cloud Storage

on:
  push:
    branches:
      - main

env:
  GOOGLE_APPLICATION_CREDENTIALS: ${{ secrets.GOOGLE_APPLICATION_CREDENTIALS }}

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - id: 'auth'
      name: 'Authenticate to Google Cloud'
      uses: 'google-github-actions/auth@v1'
      with:
        credentials_json: '${{ secrets.GOOGLE_APPLICATION_CREDENTIALS}}'

    - name: Build application
      run: |
        # Add your build commands here

    - name: Deploy to Google Cloud Storage
      run: |
        # Add your deployment commands here
        gsutil cp -n -r archive/* gs://archive_homepage

        