name: Send mails

on:
  schedule:
    - cron: '* * * * *'

env:
  GOOGLE_APPLICATION_CREDENTIALS: ${{ secrets.GOOGLE_APPLICATION_CREDENTIALS }}
  BACKUP_CLIENT_ID: ${{ secrets.BACKUP_CLIENT_ID }}
  BACKUP_CLIENT_EMAIL: ${{ secrets.BACKUP_CLIENT_EMAIL }}
  BACKUP_PRIVATE_KEY: ${{ secrets.BACKUP_PRIVATE_KEY }}
  BACKUP_PRIVATE_KEY_ID: ${{ secrets.BACKUP_PRIVATE_KEY_ID }}

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.8

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r handler/requirements.txt

    - name: Run Python script
      run: python handler/mailsRR.py